version: "3.9"
services:
  api:
    build: .
    command: uvicorn api.app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./.chroma:/app/.chroma
      - ./project_docs:/app/project_docs
      - ./.env:/app/.env
  ui:
    build: .
    command: streamlit run ui/app.py --server.port 8501 --server.address 0.0.0.0
    environment:
      - API_BASE=http://api:8000
    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - ./.chroma:/app/.chroma
      - ./project_docs:/app/project_docs
      - ./.env:/app/.env
